import { BackofficeBook } from '@/types/backoffice';

export const mockBooks: BackofficeBook[] = [
  {
    id: 'book-1',
    name: 'Book Allan Silva - 2025',
    year: 2025,
    owner: {
      id: 'user-1',
      name: 'Allan Silva',
      type: 'person',
      email: 'allan.silva@suno.com.br',
      role: 'Head de Dados e CRM',
    },
    description: 'Book de indicadores para o Head de Dados e CRM',
    indicators: [
      {
        id: 'bi-1',
        indicator_id: '1',
        indicator_name: 'Leads Qualificados Status Invest',
        indicator_format: 'number',
        indicator_direction: 'up',
        indicator_tags: [
          { id: '2', name: 'Operacional', category: 'type', color: '#666666' },
          { id: '13', name: 'Status Invest', category: 'business_unit', color: '#d42126' },
        ],
        display_order: 1,
        goals: {
          jan: 100,
          feb: 100,
          mar: 100,
          apr: 110,
          may: 110,
          jun: 110,
          jul: 120,
          aug: 120,
          sep: 120,
          oct: 130,
          nov: 130,
          dec: 130,
        },
        has_missing_goals: false,
        missing_goals_count: 0,
        current_performance: 94,
        is_achieving: false,
      },
      {
        id: 'bi-2',
        indicator_id: '2',
        indicator_name: 'Taxa de Conversão Advisory',
        indicator_format: 'percentage',
        indicator_direction: 'up',
        indicator_tags: [
          { id: '1', name: 'Estratégico', category: 'type', color: '#d42126' },
          { id: '11', name: 'Advisory', category: 'business_unit', color: '#d42126' },
        ],
        display_order: 2,
        goals: {
          jan: 25,
          feb: 25,
          mar: 26,
          apr: 27,
          may: 28,
          jun: 28,
          jul: 30,
          aug: 30,
          sep: 31,
          oct: 32,
          nov: 32,
          dec: 33,
        },
        has_missing_goals: false,
        missing_goals_count: 0,
        current_performance: 106,
        is_achieving: true,
      },
      {
        id: 'bi-3',
        indicator_id: '3',
        indicator_name: 'Budget Utilizado - Research',
        indicator_format: 'currency',
        indicator_direction: 'down',
        indicator_tags: [
          { id: '2', name: 'Operacional', category: 'type', color: '#666666' },
          { id: '10', name: 'Research', category: 'business_unit', color: '#d42126' },
        ],
        display_order: 3,
        goals: {
          jan: 300000,
          feb: 300000,
          mar: 300000,
          // Sem metas para os outros meses
        },
        has_missing_goals: true,
        missing_goals_count: 9,
        current_performance: 97,
        is_achieving: true,
      },
      {
        id: 'bi-4',
        indicator_id: '4',
        indicator_name: 'Média de Atingimento - Marketing Makers',
        indicator_format: 'percentage',
        indicator_direction: 'up',
        indicator_tags: [
          { id: '1', name: 'Estratégico', category: 'type', color: '#d42126' },
          { id: '15', name: 'Marketing Makers', category: 'business_unit', color: '#d42126' },
        ],
        display_order: 4,
        goals: {
          jan: 85,
          feb: 85,
          mar: 87,
          apr: 88,
          may: 90,
          jun: 90,
          jul: 92,
          aug: 92,
          sep: 93,
          oct: 95,
          nov: 95,
          dec: 95,
        },
        has_missing_goals: false,
        missing_goals_count: 0,
        current_performance: 98,
        is_achieving: true,
      },
    ],
    is_active: true,
    total_indicators: 4,
    indicators_with_missing_goals: 1,
    overall_performance: 99,
    indicators_achieving: 3,
    performance_level: 'excellent',
    active_quarters: [1, 2, 3, 4],
    current_quarter: 1,
    history: [
      {
        quarter: 1,
        year: 2025,
        indicators: ['1', '2', '3', '4'],
        changed_by: 'Admin FP&A',
        changed_at: new Date('2025-01-01'),
      },
    ],
    created_by: 'admin-1',
    created_by_name: 'Admin FP&A',
    created_at: new Date('2025-01-01'),
    updated_at: new Date('2025-01-15'),
  },
  {
    id: 'book-2',
    name: 'Book Time de Dados - 2025',
    year: 2025,
    owner: {
      id: 'team-1',
      name: 'Time de Dados',
      type: 'team',
      team_members_count: 8,
    },
    description: 'Book coletivo do Time de Dados',
    indicators: [
      {
        id: 'bi-5',
        indicator_id: '5',
        indicator_name: 'Qualidade de Código - Tecnologia',
        indicator_format: 'percentage',
        indicator_direction: 'up',
        indicator_tags: [
          { id: '2', name: 'Operacional', category: 'type', color: '#666666' },
          { id: '20', name: 'Tecnologia', category: 'support_area', color: '#4b4b4b' },
        ],
        display_order: 1,
        goals: {
          jan: 85,
          feb: 85,
          mar: 87,
          apr: 88,
          may: 90,
          jun: 90,
          jul: 92,
          aug: 92,
          sep: 93,
          oct: 95,
          nov: 95,
          dec: 95,
        },
        has_missing_goals: false,
        missing_goals_count: 0,
        current_performance: 87,
        is_achieving: true,
      },
      {
        id: 'bi-6',
        indicator_id: '1',
        indicator_name: 'Leads Qualificados Status Invest',
        indicator_format: 'number',
        indicator_direction: 'up',
        indicator_tags: [
          { id: '2', name: 'Operacional', category: 'type', color: '#666666' },
          { id: '13', name: 'Status Invest', category: 'business_unit', color: '#d42126' },
        ],
        display_order: 2,
        goals: {
          jan: 500,
          feb: 500,
          mar: 520,
          apr: 550,
          may: 550,
          jun: 570,
          jul: 600,
          aug: 600,
          sep: 620,
          oct: 650,
          nov: 650,
          dec: 680,
        },
        has_missing_goals: false,
        missing_goals_count: 0,
        current_performance: 92,
        is_achieving: false,
      },
    ],
    is_active: true,
    total_indicators: 2,
    indicators_with_missing_goals: 0,
    overall_performance: 90,
    indicators_achieving: 1,
    performance_level: 'good',
    active_quarters: [1, 2, 3, 4],
    current_quarter: 1,
    created_by: 'admin-1',
    created_by_name: 'Admin FP&A',
    created_at: new Date('2025-01-05'),
    updated_at: new Date('2025-01-10'),
  },
  {
    id: 'book-3',
    name: 'Book Maria Santos - 2025',
    year: 2025,
    owner: {
      id: 'user-2',
      name: 'Maria Santos',
      type: 'person',
      email: 'maria.santos@suno.com.br',
      role: 'Gerente de Produto',
    },
    indicators: [
      {
        id: 'bi-7',
        indicator_id: '7',
        indicator_name: 'Produção de Conteúdo - Mídias',
        indicator_format: 'number',
        indicator_direction: 'up',
        indicator_tags: [
          { id: '2', name: 'Operacional', category: 'type', color: '#666666' },
          { id: '16', name: 'Mídias', category: 'business_unit', color: '#d42126' },
        ],
        display_order: 1,
        goals: {
          jan: 50,
          feb: 50,
          mar: 55,
          // Sem metas definidas para o resto do ano
        },
        has_missing_goals: true,
        missing_goals_count: 9,
        current_performance: 78,
        is_achieving: false,
      },
      {
        id: 'bi-8',
        indicator_id: '2',
        indicator_name: 'Taxa de Conversão Advisory',
        indicator_format: 'percentage',
        indicator_direction: 'up',
        indicator_tags: [
          { id: '1', name: 'Estratégico', category: 'type', color: '#d42126' },
          { id: '11', name: 'Advisory', category: 'business_unit', color: '#d42126' },
        ],
        display_order: 2,
        goals: {
          jan: 20,
          feb: 20,
          mar: 22,
          apr: 23,
          may: 25,
          jun: 25,
          // Sem metas para Q3 e Q4
        },
        has_missing_goals: true,
        missing_goals_count: 6,
        current_performance: 82,
        is_achieving: true,
      },
      {
        id: 'bi-9',
        indicator_id: '6',
        indicator_name: 'Compliance - Eleven',
        indicator_format: 'percentage',
        indicator_direction: 'up',
        indicator_tags: [
          { id: '1', name: 'Estratégico', category: 'type', color: '#d42126' },
          { id: '14', name: 'Eleven', category: 'business_unit', color: '#d42126' },
        ],
        display_order: 3,
        goals: {
          jan: 95,
          feb: 95,
          mar: 96,
          apr: 96,
          may: 97,
          jun: 97,
          jul: 98,
          aug: 98,
          sep: 98,
          oct: 99,
          nov: 99,
          dec: 99,
        },
        has_missing_goals: false,
        missing_goals_count: 0,
        current_performance: 75,
        is_achieving: false,
      },
    ],
    is_active: true,
    total_indicators: 3,
    indicators_with_missing_goals: 2,
    overall_performance: 78,
    indicators_achieving: 1,
    performance_level: 'regular',
    active_quarters: [1, 2, 3, 4],
    current_quarter: 1,
    created_by: 'admin-1',
    created_by_name: 'Admin FP&A',
    created_at: new Date('2025-01-08'),
    updated_at: new Date('2025-01-12'),
  },
  {
    id: 'book-4',
    name: 'Book Time Marketing - 2025',
    year: 2025,
    owner: {
      id: 'team-2',
      name: 'Time de Marketing',
      type: 'team',
      team_members_count: 12,
    },
    indicators: [
      {
        id: 'bi-10',
        indicator_id: '4',
        indicator_name: 'Média de Atingimento - Marketing Makers',
        indicator_format: 'percentage',
        indicator_direction: 'up',
        indicator_tags: [
          { id: '1', name: 'Estratégico', category: 'type', color: '#d42126' },
          { id: '15', name: 'Marketing Makers', category: 'business_unit', color: '#d42126' },
        ],
        display_order: 1,
        goals: {
          jan: 80,
          feb: 80,
          mar: 82,
          apr: 83,
          may: 85,
          jun: 85,
          jul: 87,
          aug: 87,
          sep: 88,
          oct: 90,
          nov: 90,
          dec: 92,
        },
        has_missing_goals: false,
        missing_goals_count: 0,
        current_performance: 65,
        is_achieving: false,
      },
    ],
    is_active: true,
    total_indicators: 1,
    indicators_with_missing_goals: 0,
    overall_performance: 65,
    indicators_achieving: 0,
    performance_level: 'critical',
    active_quarters: [1, 2, 3, 4],
    current_quarter: 1,
    created_by: 'admin-1',
    created_by_name: 'Admin FP&A',
    created_at: new Date('2025-01-10'),
    updated_at: new Date('2025-01-14'),
  },
];

