import { BackofficeIndicator, IndicatorInBook } from '@/types/backoffice';

export const mockIndicators: BackofficeIndicator[] = [
  {
    id: '1',
    name: 'Leads Qualificados Status Invest',
    description: 'Número de leads qualificados pelo time de vendas do Status Invest',
    notes: 'Considerar apenas leads com score > 70',
    format: 'number',
    direction: 'up',
    status: 'validated',
    aggregation_type: 'sum',
    tags: [
      { id: '2', name: 'Operacional', category: 'type', color: '#666666' },
      { id: '13', name: 'Status Invest', category: 'business_unit', color: '#d42126' },
      { id: '24', name: 'Vendas Ativas', category: 'support_area', color: '#4b4b4b' },
    ],
    created_by: 'admin-1',
    created_by_name: 'Admin FP&A',
    created_at: new Date('2025-01-01'),
    updated_at: new Date('2025-01-15'),
    total_books: 12,
    average_achievement: 94,
    books: [
      {
        book_id: 'book-1',
        book_name: 'Book Allan Silva',
        owner_name: 'Allan Silva',
        is_manager: true,
        achievement_rate: 98,
      },
      {
        book_id: 'book-2',
        book_name: 'Book Maria Santos',
        owner_name: 'Maria Santos',
        is_manager: true,
        achievement_rate: 92,
      },
    ],
  },
  {
    id: '2',
    name: 'Taxa de Conversão Advisory',
    description: 'Percentual de leads que se tornam clientes no Advisory',
    format: 'percentage',
    direction: 'up',
    status: 'validated',
    aggregation_type: 'average',
    tags: [
      { id: '1', name: 'Estratégico', category: 'type', color: '#d42126' },
      { id: '11', name: 'Advisory', category: 'business_unit', color: '#d42126' },
      { id: '25', name: 'Inbound', category: 'support_area', color: '#666666' },
    ],
    created_by: 'admin-1',
    created_by_name: 'Admin FP&A',
    created_at: new Date('2025-01-05'),
    updated_at: new Date('2025-01-10'),
    total_books: 8,
    average_achievement: 87,
  },
  {
    id: '3',
    name: 'Budget Utilizado - Research',
    description: 'Valor total do orçamento utilizado pela área de Research',
    notes: 'Incluir todas as despesas operacionais',
    format: 'currency',
    direction: 'down',
    status: 'validated',
    aggregation_type: 'sum',
    tags: [
      { id: '2', name: 'Operacional', category: 'type', color: '#666666' },
      { id: '10', name: 'Research', category: 'business_unit', color: '#d42126' },
      { id: '26', name: 'Financeiro', category: 'support_area', color: '#4b4b4b' },
    ],
    created_by: 'admin-1',
    created_by_name: 'Admin FP&A',
    created_at: new Date('2024-12-01'),
    updated_at: new Date('2025-01-12'),
    total_books: 15,
    average_achievement: 91,
  },
  {
    id: '4',
    name: 'Média de Atingimento - Marketing Makers',
    description: 'Média de atingimento de todos os indicadores do Marketing Makers',
    format: 'percentage',
    direction: 'up',
    status: 'validated',
    aggregation_type: 'average',
    aggregated_indicators: ['1', '2', '3'],
    tags: [
      { id: '1', name: 'Estratégico', category: 'type', color: '#d42126' },
      { id: '15', name: 'Marketing Makers', category: 'business_unit', color: '#d42126' },
      { id: '21', name: 'Marketing', category: 'support_area', color: '#666666' },
    ],
    created_by: 'admin-1',
    created_by_name: 'Admin FP&A',
    created_at: new Date('2025-01-10'),
    updated_at: new Date('2025-01-14'),
    total_books: 5,
    average_achievement: 92,
  },
  {
    id: '5',
    name: 'Qualidade de Código - Tecnologia',
    description: 'Score de qualidade do código (SonarQube) da área de Tecnologia',
    format: 'percentage',
    direction: 'up',
    status: 'in_construction',
    aggregation_type: 'average',
    tags: [
      { id: '2', name: 'Operacional', category: 'type', color: '#666666' },
      { id: '20', name: 'Tecnologia', category: 'support_area', color: '#4b4b4b' },
    ],
    created_by: 'admin-1',
    created_by_name: 'Admin FP&A',
    created_at: new Date('2025-01-18'),
    updated_at: new Date('2025-01-18'),
    total_books: 0,
    average_achievement: 0,
  },
  {
    id: '6',
    name: 'Compliance - Eleven',
    description: 'Indicadores de compliance e conformidade regulatória do Eleven',
    format: 'percentage',
    direction: 'up',
    status: 'under_review',
    aggregation_type: 'average',
    tags: [
      { id: '1', name: 'Estratégico', category: 'type', color: '#d42126' },
      { id: '14', name: 'Eleven', category: 'business_unit', color: '#d42126' },
      { id: '27', name: 'Compliance', category: 'support_area', color: '#666666' },
      { id: '28', name: 'Jurídico', category: 'support_area', color: '#4b4b4b' },
    ],
    created_by: 'admin-1',
    created_by_name: 'Admin FP&A',
    created_at: new Date('2025-01-16'),
    updated_at: new Date('2025-01-17'),
    total_books: 3,
    average_achievement: 78,
  },
  {
    id: '7',
    name: 'Produção de Conteúdo - Mídias',
    description: 'Volume de conteúdo produzido pela área de Mídias',
    format: 'number',
    direction: 'up',
    status: 'validated',
    aggregation_type: 'sum',
    tags: [
      { id: '2', name: 'Operacional', category: 'type', color: '#666666' },
      { id: '16', name: 'Mídias', category: 'business_unit', color: '#d42126' },
      { id: '31', name: 'Audio Visual', category: 'support_area', color: '#666666' },
      { id: '23', name: 'Social', category: 'support_area', color: '#666666' },
    ],
    created_by: 'admin-1',
    created_by_name: 'Admin FP&A',
    created_at: new Date('2025-01-08'),
    updated_at: new Date('2025-01-12'),
    total_books: 6,
    average_achievement: 100,
  },
];

