import { TeamBook } from '@/types/indicator';

export const mockTeamBooks: TeamBook[] = [
  {
    id: 'book-allan-head',
    owner: {
      id: 'allan',
      name: 'Allan Silva',
      type: 'person',
      role: 'Head de Dados e CRM',
    },
    data: {
      indicators: [
        {
          id: '1',
          name: 'Entregas Estratégicas',
          unit: '%',
          direction: 'up',
          accumulated: {
            meta: 90,
            real: 85,
            percentage: 94,
          },
          months: {
            jan: { meta: 90, real: 85, percentage: 94 },
            feb: { meta: 90, real: 90, percentage: 100 },
            mar: { meta: 90, real: 80, percentage: 89 },
            apr: { meta: 90, real: 85, percentage: 94 },
            may: { meta: 90, real: 90, percentage: 100 },
            jun: { meta: 90, real: 85, percentage: 94 },
            jul: { meta: 90, real: 0, percentage: 0 },
            aug: { meta: 90, real: 0, percentage: 0 },
            sep: { meta: 90, real: 0, percentage: 0 },
            oct: { meta: 90, real: 0, percentage: 0 },
            nov: { meta: 90, real: 0, percentage: 0 },
            dec: { meta: 90, real: 0, percentage: 0 },
          },
        },
        {
          id: '2',
          name: 'Satisfação do Cliente',
          unit: '%',
          direction: 'up',
          accumulated: {
            meta: 85,
            real: 88,
            percentage: 104,
          },
          months: {
            jan: { meta: 85, real: 88, percentage: 104 },
            feb: { meta: 85, real: 90, percentage: 106 },
            mar: { meta: 85, real: 87, percentage: 102 },
            apr: { meta: 85, real: 88, percentage: 104 },
            may: { meta: 85, real: 89, percentage: 105 },
            jun: { meta: 85, real: 86, percentage: 101 },
            jul: { meta: 85, real: 0, percentage: 0 },
            aug: { meta: 85, real: 0, percentage: 0 },
            sep: { meta: 85, real: 0, percentage: 0 },
            oct: { meta: 85, real: 0, percentage: 0 },
            nov: { meta: 85, real: 0, percentage: 0 },
            dec: { meta: 85, real: 0, percentage: 0 },
          },
        },
        {
          id: '3',
          name: 'Budget',
          unit: 'R$',
          direction: 'down',
          accumulated: {
            meta: 1500000,
            real: 1350000,
            percentage: 90,
          },
          months: {
            jan: { meta: 250000, real: 225000, percentage: 90 },
            feb: { meta: 250000, real: 220000, percentage: 88 },
            mar: { meta: 250000, real: 230000, percentage: 92 },
            apr: { meta: 250000, real: 225000, percentage: 90 },
            may: { meta: 250000, real: 225000, percentage: 90 },
            jun: { meta: 250000, real: 225000, percentage: 90 },
            jul: { meta: 250000, real: 0, percentage: 0 },
            aug: { meta: 250000, real: 0, percentage: 0 },
            sep: { meta: 250000, real: 0, percentage: 0 },
            oct: { meta: 250000, real: 0, percentage: 0 },
            nov: { meta: 250000, real: 0, percentage: 0 },
            dec: { meta: 250000, real: 0, percentage: 0 },
          },
        },
      ],
    },
  },
  {
    id: 'book-time-dados',
    owner: {
      id: 'time-dados',
      name: 'Time de Dados',
      type: 'team',
      teamName: 'Time de Dados',
    },
    data: {
      indicators: [
        {
          id: '1',
          name: 'Qualidade dos Dados',
          unit: '%',
          direction: 'up',
          accumulated: {
            meta: 95,
            real: 92,
            percentage: 97,
          },
          months: {
            jan: { meta: 95, real: 92, percentage: 97 },
            feb: { meta: 95, real: 93, percentage: 98 },
            mar: { meta: 95, real: 91, percentage: 96 },
            apr: { meta: 95, real: 92, percentage: 97 },
            may: { meta: 95, real: 94, percentage: 99 },
            jun: { meta: 95, real: 90, percentage: 95 },
            jul: { meta: 95, real: 0, percentage: 0 },
            aug: { meta: 95, real: 0, percentage: 0 },
            sep: { meta: 95, real: 0, percentage: 0 },
            oct: { meta: 95, real: 0, percentage: 0 },
            nov: { meta: 95, real: 0, percentage: 0 },
            dec: { meta: 95, real: 0, percentage: 0 },
          },
        },
        {
          id: '2',
          name: 'Pipelines Entregues',
          unit: '#',
          direction: 'up',
          accumulated: {
            meta: 12,
            real: 11,
            percentage: 92,
          },
          months: {
            jan: { meta: 2, real: 2, percentage: 100 },
            feb: { meta: 2, real: 2, percentage: 100 },
            mar: { meta: 2, real: 2, percentage: 100 },
            apr: { meta: 2, real: 1, percentage: 50 },
            may: { meta: 2, real: 2, percentage: 100 },
            jun: { meta: 2, real: 2, percentage: 100 },
            jul: { meta: 2, real: 0, percentage: 0 },
            aug: { meta: 2, real: 0, percentage: 0 },
            sep: { meta: 2, real: 0, percentage: 0 },
            oct: { meta: 2, real: 0, percentage: 0 },
            nov: { meta: 2, real: 0, percentage: 0 },
            dec: { meta: 2, real: 0, percentage: 0 },
          },
        },
      ],
    },
  },
  {
    id: 'book-time-crm',
    owner: {
      id: 'time-crm',
      name: 'Squad CRM',
      type: 'team',
      teamName: 'Squad CRM',
    },
    data: {
      indicators: [
        {
          id: '1',
          name: 'Conversão de Leads',
          unit: '%',
          direction: 'up',
          accumulated: {
            meta: 25,
            real: 28,
            percentage: 112,
          },
          months: {
            jan: { meta: 25, real: 28, percentage: 112 },
            feb: { meta: 25, real: 27, percentage: 108 },
            mar: { meta: 25, real: 29, percentage: 116 },
            apr: { meta: 25, real: 28, percentage: 112 },
            may: { meta: 25, real: 30, percentage: 120 },
            jun: { meta: 25, real: 26, percentage: 104 },
            jul: { meta: 25, real: 0, percentage: 0 },
            aug: { meta: 25, real: 0, percentage: 0 },
            sep: { meta: 25, real: 0, percentage: 0 },
            oct: { meta: 25, real: 0, percentage: 0 },
            nov: { meta: 25, real: 0, percentage: 0 },
            dec: { meta: 25, real: 0, percentage: 0 },
          },
        },
        {
          id: '2',
          name: 'Tempo de Resposta',
          unit: 'H$',
          direction: 'down',
          accumulated: {
            meta: 24,
            real: 18,
            percentage: 75,
          },
          months: {
            jan: { meta: 24, real: 18, percentage: 75 },
            feb: { meta: 24, real: 20, percentage: 83 },
            mar: { meta: 24, real: 17, percentage: 71 },
            apr: { meta: 24, real: 19, percentage: 79 },
            may: { meta: 24, real: 16, percentage: 67 },
            jun: { meta: 24, real: 18, percentage: 75 },
            jul: { meta: 24, real: 0, percentage: 0 },
            aug: { meta: 24, real: 0, percentage: 0 },
            sep: { meta: 24, real: 0, percentage: 0 },
            oct: { meta: 24, real: 0, percentage: 0 },
            nov: { meta: 24, real: 0, percentage: 0 },
            dec: { meta: 24, real: 0, percentage: 0 },
          },
        },
        {
          id: '3',
          name: 'NPS',
          unit: '#',
          direction: 'up',
          accumulated: {
            meta: 70,
            real: 75,
            percentage: 107,
          },
          months: {
            jan: { meta: 70, real: 75, percentage: 107 },
            feb: { meta: 70, real: 73, percentage: 104 },
            mar: { meta: 70, real: 76, percentage: 109 },
            apr: { meta: 70, real: 74, percentage: 106 },
            may: { meta: 70, real: 77, percentage: 110 },
            jun: { meta: 70, real: 75, percentage: 107 },
            jul: { meta: 70, real: 0, percentage: 0 },
            aug: { meta: 70, real: 0, percentage: 0 },
            sep: { meta: 70, real: 0, percentage: 0 },
            oct: { meta: 70, real: 0, percentage: 0 },
            nov: { meta: 70, real: 0, percentage: 0 },
            dec: { meta: 70, real: 0, percentage: 0 },
          },
        },
      ],
    },
  },
  {
    id: 'book-maria-gerente',
    owner: {
      id: 'maria',
      name: 'Maria Santos',
      type: 'person',
      role: 'Gerente de Produto',
    },
    data: {
      indicators: [
        {
          id: '1',
          name: 'Features Entregues',
          unit: '#',
          direction: 'up',
          accumulated: {
            meta: 18,
            real: 16,
            percentage: 89,
          },
          months: {
            jan: { meta: 3, real: 3, percentage: 100 },
            feb: { meta: 3, real: 2, percentage: 67 },
            mar: { meta: 3, real: 3, percentage: 100 },
            apr: { meta: 3, real: 3, percentage: 100 },
            may: { meta: 3, real: 2, percentage: 67 },
            jun: { meta: 3, real: 3, percentage: 100 },
            jul: { meta: 3, real: 0, percentage: 0 },
            aug: { meta: 3, real: 0, percentage: 0 },
            sep: { meta: 3, real: 0, percentage: 0 },
            oct: { meta: 3, real: 0, percentage: 0 },
            nov: { meta: 3, real: 0, percentage: 0 },
            dec: { meta: 3, real: 0, percentage: 0 },
          },
        },
        {
          id: '2',
          name: 'Satisfação dos Stakeholders',
          unit: '%',
          direction: 'up',
          accumulated: {
            meta: 80,
            real: 85,
            percentage: 106,
          },
          months: {
            jan: { meta: 80, real: 85, percentage: 106 },
            feb: { meta: 80, real: 83, percentage: 104 },
            mar: { meta: 80, real: 87, percentage: 109 },
            apr: { meta: 80, real: 84, percentage: 105 },
            may: { meta: 80, real: 86, percentage: 108 },
            jun: { meta: 80, real: 85, percentage: 106 },
            jul: { meta: 80, real: 0, percentage: 0 },
            aug: { meta: 80, real: 0, percentage: 0 },
            sep: { meta: 80, real: 0, percentage: 0 },
            oct: { meta: 80, real: 0, percentage: 0 },
            nov: { meta: 80, real: 0, percentage: 0 },
            dec: { meta: 80, real: 0, percentage: 0 },
          },
        },
      ],
    },
  },
];

