import { BookData } from '@/types/indicator';

export const mockBookData: BookData = {
  indicators: [
    {
      id: '1',
      name: '(ACV) Indicadores de negócio',
      unit: '%',
      direction: 'up',
      accumulated: {
        meta: 80,
        real: 46,
        percentage: 58,
      },
      months: {
        jan: { meta: 80, real: 80, percentage: 100 },
        feb: { meta: 80, real: 80, percentage: 100 },
        mar: { meta: 80, real: 50, percentage: 63 },
        apr: { meta: 80, real: 33, percentage: 41 },
        may: { meta: 80, real: 50, percentage: 63 },
        jun: { meta: 80, real: 16, percentage: 20 },
        jul: { meta: 80, real: 0, percentage: 0 },
        aug: { meta: 80, real: 0, percentage: 0 },
        sep: { meta: 80, real: 0, percentage: 0 },
        oct: { meta: 80, real: 0, percentage: 0 },
        nov: { meta: 80, real: 0, percentage: 0 },
        dec: { meta: 80, real: 0, percentage: 0 },
      },
    },
    {
      id: '2',
      name: 'Entrega das Squads',
      unit: '#',
      direction: 'up',
      accumulated: {
        meta: 80,
        real: 75,
        percentage: 94,
      },
      months: {
        jan: { meta: 80, real: 75, percentage: 94 },
        feb: { meta: 80, real: 75, percentage: 94 },
        mar: { meta: 80, real: 75, percentage: 94 },
        apr: { meta: 80, real: 75, percentage: 94 },
        may: { meta: 80, real: 75, percentage: 94 },
        jun: { meta: 80, real: 75, percentage: 94 },
        jul: { meta: 80, real: 0, percentage: 0 },
        aug: { meta: 80, real: 0, percentage: 0 },
        sep: { meta: 80, real: 0, percentage: 0 },
        oct: { meta: 80, real: 0, percentage: 0 },
        nov: { meta: 80, real: 0, percentage: 0 },
        dec: { meta: 80, real: 0, percentage: 0 },
      },
    },
    {
      id: '3',
      name: 'Qualidade de entrega',
      unit: '%',
      direction: 'up',
      accumulated: {
        meta: 80,
        real: 75,
        percentage: 94,
      },
      months: {
        jan: { meta: 80, real: 75, percentage: 94 },
        feb: { meta: 80, real: 75, percentage: 94 },
        mar: { meta: 80, real: 75, percentage: 94 },
        apr: { meta: 80, real: 75, percentage: 94 },
        may: { meta: 80, real: 75, percentage: 94 },
        jun: { meta: 80, real: 75, percentage: 94 },
        jul: { meta: 80, real: 0, percentage: 0 },
        aug: { meta: 80, real: 0, percentage: 0 },
        sep: { meta: 80, real: 0, percentage: 0 },
        oct: { meta: 80, real: 0, percentage: 0 },
        nov: { meta: 80, real: 0, percentage: 0 },
        dec: { meta: 80, real: 0, percentage: 0 },
      },
    },
    {
      id: '4',
      name: 'Orçamento',
      unit: 'R$',
      direction: 'down',
      accumulated: {
        meta: 2380934,
        real: 1968048,
        percentage: 83,
      },
      months: {
        jan: { meta: 376551, real: 335434, percentage: 89 },
        feb: { meta: 379143, real: 313440, percentage: 83 },
        mar: { meta: 490173, real: 310173, percentage: 63 },
        apr: { meta: 393284, real: 313912, percentage: 80 },
        may: { meta: 345026, real: 357369, percentage: 104 },
        jun: { meta: 396757, real: 337720, percentage: 85 },
        jul: { meta: 362486, real: 0, percentage: 0 },
        aug: { meta: 362387, real: 0, percentage: 0 },
        sep: { meta: 365390, real: 0, percentage: 0 },
        oct: { meta: 374500, real: 0, percentage: 0 },
        nov: { meta: 358588, real: 0, percentage: 0 },
        dec: { meta: 358774, real: 0, percentage: 0 },
      },
    },
  ],
};

