import { BackofficeIndicator, IndicatorInBook } from '@/types/backoffice';

export const mockIndicators: BackofficeIndicator[] = [
  {
    id: '1',
    name: 'Leads Qualificados',
    description: 'Número de leads qualificados pelo time de vendas',
    notes: 'Considerar apenas leads com score > 70',
    format: 'number',
    direction: 'up',
    status: 'validated',
    aggregation_type: 'sum',
    tags: [
      { id: '1', name: 'Operacional', color: '#666666' },
      { id: '2', name: 'Vendas', color: '#d42126' },
    ],
    created_by: 'admin-1',
    created_by_name: 'Admin FP&A',
    created_at: new Date('2025-01-01'),
    updated_at: new Date('2025-01-15'),
    total_books: 12,
    average_achievement: 94,
    books: [
      {
        book_id: 'book-1',
        book_name: 'Book Allan Silva',
        owner_name: 'Allan Silva',
        is_manager: true,
        achievement_rate: 98,
      },
      {
        book_id: 'book-2',
        book_name: 'Book Maria Santos',
        owner_name: 'Maria Santos',
        is_manager: true,
        achievement_rate: 92,
      },
    ],
  },
  {
    id: '2',
    name: 'Taxa de Conversão',
    description: 'Percentual de leads que se tornam clientes',
    format: 'percentage',
    direction: 'up',
    status: 'validated',
    aggregation_type: 'average',
    tags: [
      { id: '1', name: 'Estratégico', color: '#4b4b4b' },
      { id: '2', name: 'Vendas', color: '#d42126' },
    ],
    created_by: 'admin-1',
    created_by_name: 'Admin FP&A',
    created_at: new Date('2025-01-05'),
    updated_at: new Date('2025-01-10'),
    total_books: 8,
    average_achievement: 87,
  },
  {
    id: '3',
    name: 'Budget Utilizado',
    description: 'Valor total do orçamento utilizado no período',
    notes: 'Incluir todas as despesas operacionais',
    format: 'currency',
    direction: 'down',
    status: 'validated',
    aggregation_type: 'sum',
    tags: [
      { id: '3', name: 'Financeiro', color: '#d42126' },
    ],
    created_by: 'admin-1',
    created_by_name: 'Admin FP&A',
    created_at: new Date('2024-12-01'),
    updated_at: new Date('2025-01-12'),
    total_books: 15,
    average_achievement: 91,
  },
  {
    id: '4',
    name: 'Média de Atingimento do Time',
    description: 'Média de atingimento de todos os indicadores do time',
    format: 'percentage',
    direction: 'up',
    status: 'validated',
    aggregation_type: 'average',
    aggregated_indicators: ['1', '2', '3'],
    tags: [
      { id: '4', name: 'Estratégico', color: '#4b4b4b' },
    ],
    created_by: 'admin-1',
    created_by_name: 'Admin FP&A',
    created_at: new Date('2025-01-10'),
    updated_at: new Date('2025-01-14'),
    total_books: 5,
    average_achievement: 92,
  },
  {
    id: '5',
    name: 'Qualidade de Código',
    description: 'Score de qualidade do código (SonarQube)',
    format: 'percentage',
    direction: 'up',
    status: 'in_construction',
    aggregation_type: 'average',
    tags: [
      { id: '5', name: 'Qualidade', color: '#999999' },
      { id: '6', name: 'Tech', color: '#666666' },
    ],
    created_by: 'admin-1',
    created_by_name: 'Admin FP&A',
    created_at: new Date('2025-01-18'),
    updated_at: new Date('2025-01-18'),
    total_books: 0,
    average_achievement: 0,
  },
  {
    id: '6',
    name: 'Horas de Treinamento',
    description: 'Total de horas investidas em treinamento da equipe',
    format: 'hours',
    direction: 'up',
    status: 'under_review',
    aggregation_type: 'sum',
    tags: [
      { id: '7', name: 'RH', color: '#666666' },
    ],
    created_by: 'admin-1',
    created_by_name: 'Admin FP&A',
    created_at: new Date('2025-01-16'),
    updated_at: new Date('2025-01-17'),
    total_books: 3,
    average_achievement: 78,
  },
  {
    id: '7',
    name: 'Projeto Concluído',
    description: 'Indica se o projeto foi concluído no prazo',
    format: 'boolean',
    direction: 'up',
    status: 'validated',
    aggregation_type: 'count',
    tags: [
      { id: '8', name: 'Projetos', color: '#4b4b4b' },
    ],
    created_by: 'admin-1',
    created_by_name: 'Admin FP&A',
    created_at: new Date('2025-01-08'),
    updated_at: new Date('2025-01-12'),
    total_books: 6,
    average_achievement: 100,
  },
];

